### ISSUE TITLE
ServicePricePositions from actual documents reappeared

### ISSUE THREAD

**Issue by kfina-planxy** [hellohq-io/hellohq.docs#205] opened 2024-12-09 08:41 UTC
This issue [https://github.com/hellohq-io/hellohq.docs/issues/201](https://github.com/hellohq-io/hellohq.docs/issues/201) reappeared.
I'm receiving a huge amount of articles from the `GET /v2/Services` route again.
(Maybe a merge conflict wasn't handled correctly?)

**Comment by monderino** [comment] 2024-12-09 09:15
Hey @kfina-planxy 

Thanks, I will check it immediately.

**Comment by monderino** [comment] 2024-12-09 09:48
Hey @kfina-planxy,

I tested it with my test system. Here all works fine.
Can you please provide me your domain and an example call. Then I try to verify this again.

**Comment by kfina-planxy** [comment] 2024-12-09 10:00
Hey @monderino,

domain: https://mobile-spaces.hellohq.io/

I just noticed the error only appears on 
`GET https://api.hellohq.io/v2/Services/`, but not on
`GET https://api.hellohq.io/v2/Services/{id}`.

Example Calls:
`GET https://api.hellohq.io/v2/Services/?filter=id eq 12` returns a large amount of "documentPositionEntities". 
_(I know this is not a rather useful route, but it showcases the problem well. Normally, we use this route without any params),_ 

`GET https://api.hellohq.io/v2/Services/12` only returns 2 "documentPositionEntities"

Kind regards,
Kenten Fina

**Comment by monderino** [comment] 2024-12-09 11:30
Thank you for the hint.

The issue is fixed by tomorrow.

**Closed** 2024-12-20 08:07 UTC
